
export const ALL_PERMISSIONS = [
  'dashboard:view',
  'my-tasks:view',
  'team-view:view',
  'team-view:manage',
  'projects:create',
  'projects:read',
  'projects:update',
  'projects:delete',
  'milestones:view',
  'gantt:view',
  'departments:create',
  'departments:read',
  'departments:update',
  'departments:delete',
  'teams:create',
  'teams:read',
  'teams:update',
  'teams:delete',
  'settings:manage',
  'config:manage-users',
  'config:manage-roles',
];
